# Auto-generated by project_restructuring.py

"""
Code Conductor - AI Development Environment Setup Tool
"""

from .core.work_effort.manager import WorkEffortManager
from .events import EventEmitter, Event

__version__ = "0.5.0"
__all__ = ['WorkEffortManager', 'EventEmitter', 'Event']
