#!/bin/bash
# Auto-generated test catalog - Sun Mar  9 15:43:43 PDT 2025
# This file is generated by test_discovery.sh

# Shell Tests
SHELL_TESTS=(
    "./simple_help_test.sh"
    "./test_config_system.sh"
    "./test_multi_manager.sh"
    "./tests/test_work_effort_manager_config.sh"
    "./tests/test_cc_work_e_command.sh"
    "./create_test_work_effort.sh"
    "./simple_setup_test.sh"
    "./simple_version_test.sh"
    "./test_work_effort_manager.sh"
    "./test_work_effort_commands.sh"
)

# Python Tests
PYTHON_TESTS=(
    "./tests/test_modular_architecture.py"
    "./tests/test_work_effort_manager_edge_cases.py"
    "./tests/test_modular_implementation.py"
    "./tests/test_workflow_and_performance.py"
    "./tests/test_work_effort_manager_config.py"
    "./tests/test_config_system.py"
    "./tests/test_work_effort_shorthand.py"
    "./tests/test_work_effort_edge_case_fixes.py"
)

# Simple Tests
SIMPLE_TESTS=(
    "./simple_help_test.sh"
    "./simple_setup_test.sh"
    "./simple_version_test.sh"
)

# Integration Tests
INTEGRATION_TESTS=(
    "./tests/test_modular_architecture.py"
    "./tests/test_modular_implementation.py"
    "./tests/test_work_effort_manager_config.py"
    "./tests/test_work_effort_shorthand.py"
)

# Unit Tests
UNIT_TESTS=(
    "./tests/test_modular_architecture.py"
    "./tests/test_work_effort_manager_edge_cases.py"
    "./tests/test_modular_implementation.py"
    "./tests/test_workflow_and_performance.py"
    "./tests/test_work_effort_manager_config.py"
    "./tests/test_config_system.py"
    "./tests/test_work_effort_shorthand.py"
    "./tests/test_work_effort_edge_case_fixes.py"
)

# Command Tests
COMMAND_TESTS=(
)

# Performance Tests
PERFORMANCE_TESTS=(
    "./tests/test_work_effort_manager_edge_cases.py"
    "./tests/test_workflow_and_performance.py"
)

# CLI Tests
CLI_TESTS=(
    "./tests/test_config_system.py"
)
